version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: fullcycle-php
    volumes:
      - ./:/var/www
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: fullcycle-nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge